# Generated by Django 5.2.3 on 2025-06-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="min_group",
            field=models.PositiveSmallIntegerField(
                choices=[(5, "kleine Gruppe"), (10, "große Gruppe"), (0, "unendlich")],
                default=0,
            ),
        ),
    ]
